/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as InterviewNewRouteImport } from './routes/interview.new'
import { Route as InterviewInterviewIdRouteImport } from './routes/interview.$interviewId'
import { Route as DashboardInterviewsRouteImport } from './routes/dashboard.interviews'
import { Route as DashboardHistoryRouteImport } from './routes/dashboard.history'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const InterviewNewRoute = InterviewNewRouteImport.update({
  id: '/interview/new',
  path: '/interview/new',
  getParentRoute: () => rootRouteImport,
} as any)
const InterviewInterviewIdRoute = InterviewInterviewIdRouteImport.update({
  id: '/interview/$interviewId',
  path: '/interview/$interviewId',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardInterviewsRoute = DashboardInterviewsRouteImport.update({
  id: '/interviews',
  path: '/interviews',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardHistoryRoute = DashboardHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => DashboardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/dashboard/history': typeof DashboardHistoryRoute
  '/dashboard/interviews': typeof DashboardInterviewsRoute
  '/interview/$interviewId': typeof InterviewInterviewIdRoute
  '/interview/new': typeof InterviewNewRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/dashboard/history': typeof DashboardHistoryRoute
  '/dashboard/interviews': typeof DashboardInterviewsRoute
  '/interview/$interviewId': typeof InterviewInterviewIdRoute
  '/interview/new': typeof InterviewNewRoute
  '/dashboard': typeof DashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/dashboard/history': typeof DashboardHistoryRoute
  '/dashboard/interviews': typeof DashboardInterviewsRoute
  '/interview/$interviewId': typeof InterviewInterviewIdRoute
  '/interview/new': typeof InterviewNewRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/signup'
    | '/dashboard/history'
    | '/dashboard/interviews'
    | '/interview/$interviewId'
    | '/interview/new'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/dashboard/history'
    | '/dashboard/interviews'
    | '/interview/$interviewId'
    | '/interview/new'
    | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login'
    | '/signup'
    | '/dashboard/history'
    | '/dashboard/interviews'
    | '/interview/$interviewId'
    | '/interview/new'
    | '/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  InterviewInterviewIdRoute: typeof InterviewInterviewIdRoute
  InterviewNewRoute: typeof InterviewNewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/interview/new': {
      id: '/interview/new'
      path: '/interview/new'
      fullPath: '/interview/new'
      preLoaderRoute: typeof InterviewNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/interview/$interviewId': {
      id: '/interview/$interviewId'
      path: '/interview/$interviewId'
      fullPath: '/interview/$interviewId'
      preLoaderRoute: typeof InterviewInterviewIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/interviews': {
      id: '/dashboard/interviews'
      path: '/interviews'
      fullPath: '/dashboard/interviews'
      preLoaderRoute: typeof DashboardInterviewsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/history': {
      id: '/dashboard/history'
      path: '/history'
      fullPath: '/dashboard/history'
      preLoaderRoute: typeof DashboardHistoryRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardHistoryRoute: typeof DashboardHistoryRoute
  DashboardInterviewsRoute: typeof DashboardInterviewsRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardHistoryRoute: DashboardHistoryRoute,
  DashboardInterviewsRoute: DashboardInterviewsRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  InterviewInterviewIdRoute: InterviewInterviewIdRoute,
  InterviewNewRoute: InterviewNewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
